language: java  

script:
  - mvn install -DskipTests=true

jenkins:
  pipeline_jenkinsfile: Jenkinsfile
  stash:
    - name: artifacts
      includes: target/*.war 
  collect:
    artifacts: target/*.war
