language: java  

script:
  - mvn install -DskipTests=true
  
cache:
  directories:
    - ${HOME}/.m2

jenkins:
  pipeline_jenkinsfile: Jenkinsfile
  stash:
    - name: artifacts
      includes: target/*.war 
  collect:
    artifacts: target/*.war
